# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  font: minimal
  fone_size: l

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Mengfu Han personal website'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: d-2DiStlHuG8ylMLKEiZdVSd0Ofqr-rVnKamJOpoLkI
    baidu: ''

# Site header
header:
  navbar:
    # Display the navigation bar?
    enable: true
    # Choose a built-in navigation blox or create your own
    blox: "navbar"
    # Align menu links: `left`, `center`, or `right`
    align: "right"
    # Fix the navigation bar to the top of the page
    fixed_to_top: true
    logo:
      # Logo text
      text: "Mengfu Han"
      # Logo filename in `assets/media/` folder
      filename: ""
    # Let the user choose between light or dark mode?
    show_theme_chooser: true
    # Let the user search from the navigation bar?
    show_search: true
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true
    # Show a language chooser (if you have translated your site content)?
    show_translations: false
    # If `show_translations` is enabled, do you wish to hide the current language name?
    hide_language_name: false

# Site footer
footer:
  copyright:
    notice: '© 2025 Mengfu Han.'
    license:
      enable: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  custom_css: ["css/uga.css"]

# 自定义样式
custom_css:
  - css/custom.css

